### ISSUE TITLE
Log in enter log in

### ISSUE THREAD

**Issue by yvonne-liu** [yvonne-liu/annafreud-app#52]
Right now you have to click the log in button to log in, let's have an enter option as well

Also, the log in button is actually _not super intuitive_ to me. Thoughts? @lucyrose93 @majakudlicka

**Comment by lucyrose93** [comment]
@yvonne-liu 
we can change the log in icon to text to make it more intuitive
would be nice to keep it symbolic though
if you can think of a more intuitive symbol
http://www.flaticon.com/search?word=log%20in

no point setting it to enter as it's mobile, right?

**Comment by yvonne-liu** [comment]
Fixed.
